-- 学习计划测试数据
-- 生成20条数据，其中10条end_date为今天
-- 包含已完成和未完成的计划

-- 清空原有数据
DELETE FROM public.study_plans;

-- 插入测试数据
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (1, 1, '完成作业', '学习任务：完成作业', 'daily', '数学', 'easy', '已完成', 100, '2026-01-31', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (2, 1, '复习笔记', '学习任务：复习笔记', 'weekly', '英语', 'medium', '未完成', 45, '2026-01-30', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (3, 1, '学习教材', '学习任务：学习教材', 'monthly', '语文', 'hard', '已完成', 100, '2026-01-29', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (4, 1, '准备考试', '学习任务：准备考试', 'project', '物理', 'medium', '未完成', 78, '2026-01-28', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (5, 1, '整理实验', '学习任务：整理实验', 'daily', '化学', 'easy', '已完成', 100, '2026-01-27', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (6, 1, '阅读项目', '学习任务：阅读项目', 'weekly', '生物', 'hard', '未完成', 32, '2026-01-26', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (7, 1, '练习论文', '学习任务：练习论文', 'monthly', '历史', 'medium', '已完成', 100, '2026-01-25', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (8, 1, '参加演讲', '学习任务：参加演讲', 'project', '地理', 'easy', '未完成', 56, '2026-01-24', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (9, 1, '制定计划', '学习任务：制定计划', 'daily', '计算机', 'medium', '已完成', 100, '2026-01-23', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (10, 1, '研究知识点', '学习任务：研究知识点', 'weekly', '数学', 'hard', '未完成', 67, '2026-01-22', '2026-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 其他日期的计划
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (11, 1, '完成笔记', '学习任务：完成笔记', 'monthly', '英语', 'easy', '已完成', 100, '2026-01-20', '2026-01-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (12, 1, '复习教材', '学习任务：复习教材', 'project', '语文', 'medium', '未完成', 45, '2026-01-18', '2026-01-22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (13, 1, '学习考试', '学习任务：学习考试', 'daily', '物理', 'hard', '已完成', 100, '2026-01-15', '2026-01-18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (14, 1, '准备实验', '学习任务：准备实验', 'weekly', '化学', 'easy', '未完成', 78, '2026-01-12', '2026-01-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (15, 1, '整理项目', '学习任务：整理项目', 'monthly', '生物', 'medium', '已完成', 100, '2026-01-10', '2026-01-12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (16, 1, '阅读论文', '学习任务：阅读论文', 'project', '历史', 'hard', '未完成', 32, '2026-02-02', '2026-02-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (17, 1, '练习演讲', '学习任务：练习演讲', 'daily', '地理', 'easy', '已完成', 100, '2026-02-03', '2026-02-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (18, 1, '参加计划', '学习任务：参加计划', 'weekly', '计算机', 'medium', '未完成', 56, '2026-02-05', '2026-02-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (19, 1, '制定知识点', '学习任务：制定知识点', 'monthly', '数学', 'hard', '已完成', 100, '2026-02-07', '2026-02-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.study_plans (id, user_id, title, description, plan_type, subject, difficulty, status, progress_percent, start_date, end_date, created_at, updated_at) VALUES (20, 1, '研究作业', '学习任务：研究作业', 'project', '英语', 'medium', '未完成', 67, '2026-02-10', '2026-02-28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
